


spring.datasource.url=jdbc:postgresql://db.zvnmkrcjfmrltqkoflwy.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=CKJ24012026#01111990
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=fluxo_financeiro

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=fluxo_financeiro
spring.flyway.default-schema=fluxo_financeiro
spring.flyway.create-schemas=true